[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/(
  (
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | \.direnv
    | venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | .*/_version.py
)
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 79

[tool.pytest.ini_options]
addopts = "-vv --pikachu --mypy"
testpaths = [
    "tests",
]
