version: '3.3'

networks:
  voltaire-test:

services:

  site:
    image: nginx
    volumes:
      - $PWD/dist:/usr/share/nginx/html
    networks:
      voltaire-test:
        aliases:
          - ${DOMAIN}

  verify:
    image: python:latest
    build:
      dockerfile: ${DOCKERFILE_VERIFY}
      context: .
    command: scrapy weblint ${WEBLINT_OPTS} http://${DOMAIN}/
    depends_on:
      - site
    networks:
      - voltaire-test
