version: '3.3'

services:

  site:
    image: nginx
    volumes:
      - $PWD/dist:/usr/share/nginx/html
    hostname: ${DOMAIN}

  verify:
    image: python:latest
    build:
      dockerfile: ${DOCKERFILE_VERIFY}
      context: .
    command: scrapy weblint ${WEBLINT_OPTS} http://${DOMAIN}/
    depends_on:
      - site
